### ISSUE TITLE
Percent complete should not have any decimal points

### ISSUE THREAD

**Issue by enddynayn** [AmplicaLabs/wallet-proxy#34]
When steps are added ensure that rounding is done and irrational number is not displayed.
<img width="344" alt="Screenshot 2023-08-31 at 11 35 17 AM" src="https://github.com/AmplicaLabs/wallet-proxy/assets/3433442/e3ed7a89-f5b2-43dc-99fa-25ea27579a91">

**Comment by shannonwells** [comment]
Closed with #38
